server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        hbm2ddl:
          auto: update
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_APP_PASS}
    test-connection: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: 7A24432646294A404E635266556A586E327235753778214125442A472D4B6150
  expirationHours: 24

host:
  url: "http://localhost:${server.port}"

job:
  checkBlackListTimeMs: 900000