server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/messenger_db
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASS}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_APP_PASS}
    test-connection: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: 7A24432646294A404E635266556A586E327235753778214125442A472D4B6150
  expirationHours: 24

host:
  url: "http://localhost:${server.port}"

job:
  checkBlackListTimeMs: 900000