server:
  port: 8081

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${GMAIL}
    password: ${GMAIL_APP_PASS}
    test-connection: true
    properties.mail.smtp:
      auth: true
      starttls.enable: true

jwt:
  secret: secret
  expirationHours: 24

host:
  url: "http://localhost:${server.port}"